<a href="https://colab.research.google.com/github/mohit-k39/machine-learning-algos-from-scratch/blob/main/Linear_Regression(cs229).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [3]:
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(42)

n = 1000
d = 5

X = 2 * np.random.rand(n, d)

true_theta = np.array([4, 3, -2, 1.5, 0.5])
# true_theta = np.array([2])

noise = np.random.randn(n)

y = X @ true_theta + noise

print(X.shape)
print(y.shape)

(1000, 5)
(1000,)


In [4]:
# plt.scatter(X, y)
# plt.xlabel('X')
# plt.ylabel('y')
# plt.title('Scatter Plot of X vs y')
# plt.show()

In [5]:
class LinearRegressionGradiendDescent():

    def fit(self, X, y):
        theta = np.zeros(X.shape[1])
        for i in range(1000):
            loss = (theta@X.T-y)@(theta@X.T-y)
            loss_gradient = X.T@X@theta-X.T@y
            theta = theta - 0.00001*loss_gradient
            new_loss = (theta@X.T-y)@(theta@X.T-y)
            if abs(loss - new_loss) <= 0.001:
                print(i)
                break
        return theta

class LinearRegressionClosedForm():

    def fit(self, X, y):
        theta = np.linalg.inv(X.T@X)@X.T@y
        return theta


In [6]:
lr = LinearRegressionGradiendDescent()
lrcf = LinearRegressionClosedForm()
theta_learned = lr.fit(X[:1000],y[:1000])
theta_learned_cf = lrcf.fit(X[:1000],y[:1000])

In [8]:
print(f"gradient descent solution : {theta_learned}")
print(f"closed fom solution : {theta_learned_cf}")

gradient descent solution : [ 3.9996187   2.85704623 -1.90085769  1.47409458  0.51636322]
closed fom solution : [ 4.08683655  2.90841622 -2.02463278  1.48649185  0.48729636]


In [11]:
from sklearn.linear_model import LinearRegression

model = LinearRegression(fit_intercept=False)

model.fit(X, y)

print("Gradient Descent theta:")
print(theta_learned)

print("\nclosed form theta:")
print(theta_learned_cf)

print("\nSklearn theta:")
print(model.coef_)

Gradient Descent theta:
[ 3.9996187   2.85704623 -1.90085769  1.47409458  0.51636322]

closed form theta:
[ 4.08683655  2.90841622 -2.02463278  1.48649185  0.48729636]

Sklearn theta:
[ 4.08683655  2.90841622 -2.02463278  1.48649185  0.48729636]
